config/routes.rb
Rails.application.routes.draw do

  get 'run' => 'games#run'
  get 'score' => 'games#score'
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController

  def run
    @grid = generate_grid(15).join
    @start_time = Time.now
  end

  def score
    grid = params[:grid].split("")
    @attempt = params[:attempt]
    start_time = Time.parse(params[:start_time])
    end_time = Time.now

    @ret = run_game(@attempt, grid, start_time, end_time)

  end

  private

  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
  end

  def word_in_grid?(word, grid)
    word.chars.reduce(true) { |a, e| a && (word.chars.count(e) <= grid.map(&:downcase).count(e)) }
  end

  def run_game(attempt, grid, start_time, end_time)
    ret = { time: end_time - start_time, score: 0 }
    translation = first_translation(attempt)
    no_error = !translation.nil?
    wig = word_in_grid?(attempt, grid)
    if no_error && word_in_grid?(attempt, grid)
      ret[:score] = attempt.length - (end_time - start_time).to_i
      ret[:translation] = translation
    end
    ret[:message] = message(no_error, wig)
    return ret
  end

  def message(word_exists, word_in_grid)
    if !word_exists
      return "not an english word"
    elsif !word_in_grid
      return "not in the grid"
    else
      return "well done"
    end
  end

  def first_translation(word)
    path = %w(term0 PrincipalTranslations 0 FirstTranslation term)
    path.reduce(JSON
    .parse(open("http://api.wordreference.com/0.8/80143/json/enfr/#{word}")
    .read)) { |a, e| a.nil? ? nil : a[e] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/run.html.erb
<h1>WELCOME TO THE LONGEST WORD GAME</h1>

<h2>Grid: <%= @grid %></h2>

<form action="<%= score_path %>" method="get">
  <input type="text" name="attempt">
  <input type="hidden" name="grid" value="<%= @grid %>">
  <input type="hidden" name="start_time" value="<%= @start_time %>">
  <input type="submit" value="GO">
</form>

app/views/games/score.html.erb
<h1>Your result</h1>

<ul>
  <li>Attempt: <%= @attempt%></li>
  <li>Translation: <%= @ret[:translation]%></li>
  <li>Time: <%= @ret[:time]%></li>
  <li>Message: <%= @ret[:message]%></li>
  <li>Score: <%= @ret[:score]%></li>
</ul>

<%= link_to("Restart", run_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Worthwordsgame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p>Today we are <%= Time.now.strftime("%d/%m/%Y") %><p>
<%= yield %>

</body>
</html>